#HashKnownHosts yes
#VerifyHostKeyDNS ask
# CanonicalizeHostname always
# CanonicalDomains csail.mit.edu luria.mit.edu

Match exec "echo %h | grep -qE '^[bc][0-9]+$'"
    HostName %h.private
    ProxyJump luria.mit.edu
    User benjames
  
# all  CSAIL hosts use GSSAPI
Host *.mit.edu
    User benjames
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials yes    

Host mfa-jump.csail.mit.edu jump.csail.mit.edu
    ControlMaster auto
    ControlPersist 1800
    ControlPath ~/.ssh/cm_socket/%C

Host athena.dialup.mit.edu
    ControlMaster auto
    ControlPersist 1800
    ControlPath ~/.ssh/cm_socket/%C
    
# CSAIL hosts except jumphosts get GSSAPIDelegateCredentials for AFS
Host *.csail.mit.edu  !mfa-jump.csail.mit.edu !jump.csail.mit.edu 128.52.* 128.30.* 128.31.*
    ProxyJump mfa-jump.csail.mit.edu
    ForwardAgent yes

# if you ssh to ATHENA systems
# uncomment the lines below
# and edit to include your ATHENA Username
Host !*.csail.mit.edu *.mit.edu !athena.dialup.mit.edu
    ProxyJump athena.dialup.mit.edu
    ForwardAgent yes
    PubkeyAcceptedKeyTypes +ssh-rsa

