#HashKnownHosts yes
#VerifyHostKeyDNS ask
# CanonicalizeHostname always
# CanonicalDomains csail.mit.edu luria.mit.edu

Match exec "echo %h | grep -qE '^kellislab[0-9]+'$"
    HostName %h.csail.mit.edu

Match exec "echo %h | grep -qE '^[bc][0-9]+$'"
    HostName %h.private
    ProxyJump luria.mit.edu
    User benjames

Host luria.mit.edu
    User benjames
    HostName 10.159.3.125
    ProxyJump mfa-jump.csail.mit.edu
    ControlMaster auto
    ControlPersist 1800
    ControlPath ~/.ssh/cm_socket/%C

  
# all  CSAIL hosts use GSSAPI
Host *.csail.mit.edu 128.52.* 128.30.*
  GSSAPIAuthentication yes
  User benjames


# jumps reuse existing connections to minimise DUO prompts
# "ControlPath" must exist and cannot be in AFS
#
# NOTE: if you are on a laptop or other systems that switches 
# networks the Control Socket will need to be manually removed
# in order for it to get recreated on the new network:
#
# rm ~/.ssh/cm_socket/*
#
# The symptom is new ssh session hanging prior to connection
# It is always safe to run this command though it will require 
# Duo auth on re-establish the connection.

Host mfa-jump.csail.mit.edu jump.csail.mit.edu
  ControlMaster auto
  ControlPersist 1800
  ### This directory must be manually created! ###
  ControlPath ~/.ssh/cm_socket/%C

# CSAIL hosts except jumphosts get GSSAPIDelegateCredentials for AFS
Host *.csail.mit.edu  !mfa-jump.csail.mit.edu !jump.csail.mit.edu 128.52.* 128.30.* 128.31.*
  ProxyJump mfa-jump.csail.mit.edu
  GSSAPIDelegateCredentials yes
  ForwardAgent yes

# if you ssh to ATHENA systems
# uncomment the lines below
# and edit to include your ATHENA Username
Host !*.csail.mit.edu *.mit.edu
    User benjames
    # GSSAPIAuthentication yes
    # GSSAPIDelegateCredentials yes
    PubkeyAcceptedKeyTypes +ssh-rsa
    # ControlMaster auto
    # ControlPersist 1800
    # ControlPath ~/.ssh/cm_socket/%C



