set-option -g prefix C-q
unbind-key C-b
bind-key C-q send-prefix

#set-option -g status off
set-option -g status-style fg=black,bg=magenta

if-shell '[ -n "$EPREFIX" ]' \
  "set -g default-shell \"$SHELL\"; set -g default-command \"$SHELL\"" \
  "set -g default-shell /bin/bash; set -g default-command /bin/bash"
set -g history-limit 100000
