- name: Install docker and docker-compose
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: true
  become: true
  tags: [docker]

- name: Ensure connecting user is in docker group
  ansible.builtin.user:
    name: "{{ ansible_facts.env.USER }}"
    groups: docker
    append: true
  become: true
  tags: [docker]
